version: '3.6'
services:

  activities-db:
    image: "postgres"
    container_name: activities-db
    pull_policy: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=activities
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=at

  activities-app:
    image: andrejtodorovski5/activities:latest
    container_name: activities-app
    pull_policy: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://activities-db:5432/activities
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=at
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:8080
    depends_on:
      - activities-db
  
  activities-frontend:
    image: andrejtodorovski5/activities-frontend:latest
    container_name: activities-frontend
    pull_policy: always
    ports:
      - 4200:80
    depends_on:
      - activities-app


volumes:
  postgres-data:
    driver: local