apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: activities-db
  namespace: activities
spec:
  serviceName: "activities-db"
  replicas: 1
  selector:
    matchLabels:
      app: activities-db
  volumeClaimTemplates:
  - metadata:
      name: activities-db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: my-storage-class
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        app: activities-db
    spec:
      containers:
      - name: activities-db
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: activities-configmap
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: activities-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: activities-secret
              key: POSTGRES_PASSWORD